import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Inner from "../../components/Layout/Inner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Inner>
        {/* <div className="wrapper"> */}
        <h1>About</h1>

        <div className="body">
          <p className="hero-text">
            Andy Lucas is an English author of action and adventure thrillers,
            who has lived and breathed adventure tales from the likes of
            Cussler, Higgins and Clancy, for years. RACE AMAZON: False Dawn is
            the first in his James Pace series, and was included in the
            international bestselling HOTBOX collaboration in 2016. It was also
            chosen as one of the best books of the month, on this site, when it
            first featured, in 2021. Andy is also the author of the Ian Flyn
            science fiction thrillers, and has penned poetry and a children’s
            book, which he wrote specifically for his daughter. Years of
            experience in the fields of mental health, criminal justice,
            education and environmental work, allow Andy to create diverse,
            interesting and believable characters in his books, all the time
            focusing on giving the reader a fantastic story to dive inside. He
            is married, with three children, and lives in London.
          </p>
        </div>
        {/* </div> */}
      </Inner>
    </>
  );
}
